### ISSUE TITLE
Implementar primera versión del API (v0.1)

### ISSUE THREAD

**Issue by tyronfonseca** [fabianabarca/ferias-antiguo#2]
Implementar la primera versión del API (REST) para los modelos:

- Producto
- Feria
- Horario

**Requerimientos:**

- Se usará el [Django REST framework](https://www.django-rest-framework.org/). 
- Solo se habilitarán el método de lectura: GET

**Subtasks:**

- [x] Crear serializadores de los modelos
- [x] Crear views de los modelos en el API
- [x] Testing de todos los posibles input/outputs (con la ayuda de [Postman](https://www.postman.com/))
