### ISSUE TITLE
Implementar filtros Productos API v0.1

### ISSUE THREAD

**Issue by tyronfonseca** [fabianabarca/ferias-antiguo#4]
Filtrar todos los metodos GET relacionados a Producto

**Requerimientos:**
- Los productos deben tener los siguientes filtros:
   - Filtrar por nombre común (usar el equivalente a un LIKE en SQL)
   - Filtrar por nombre científico (usar el equivalente a un LIKE en SQL)
   - Filtrar por termino que se encuentre en la descripción 
   - Filtrar por temporada específica (Ejemplo: Dec)
   - Filtrar por rango de temporada (Ejemplo: Dec-Feb)
   - Filtrar por categoría
   - Elegir que campos devolver

**Subtasks:**

- [x] Filtro Nombre Común
- [x] Filtro Nombre Científico
- [x] Filtro termino descripción
- [x] Filtro temporada específica
- [x] Filtro temporada rango
- [x] Filtro por categoría específica
- [x] Elegir que campos devolver
