### ISSUE TITLE
Implementar filtros Ferias/Horarios API v0.1

### ISSUE THREAD

**Issue by tyronfonseca** [fabianabarca/ferias-antiguo#5]
Filtrar todos los metodos GET de Ferias relacionados con los horarios

**Requerimientos:**
- Los horarios deben tener los siguientes filtros para devolver una lista de ferias:
   - Día de inicio 
   - Día final
   - Hora de inicio
   - Hora final
  
**Subtasks:**

- [x] Filtro día de inicio
- [x] Filtro día final
- [x] Filtro hora de inicio
- [x] Filtro hora final
