### ISSUE TITLE
Escribir documentación del API v0.1

### ISSUE THREAD

**Issue by tyronfonseca** [fabianabarca/ferias-antiguo#6]
Documentar el API para que sea de fácil entendimiento para cualquier persona que desee utilizarlo y así pueda hacer uso de la API.

**Requerimientos:**
- Debe estar escrito en inglés
- Se debe utilizar una herramienta fácil de utilizar y modificar (Wiki del repositorio, OpenAPI, etc.)
- Debe tener todos los posibles filtros/opciones que se puedan usar en el API
- Se debe tener una sección para los métodos no implementados (PUT, DELETE, POST) explicando que de momento no se implementarán.

**Subtasks:**

- [x] Buscar opciones para crear la documentación
- [x] Escribir/implementar documentación
- [x] Verificar que el contenido sea fácil de entender (gramática, ortografía, etc.) y se vea bien
